FROM node:20-alpine

RUN apk add --no-cache \
    libc6-compat \
    wget \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    git \
    && rm -rf /var/cache/apk/*

RUN npm install -g pnpm@latest

WORKDIR /app

ENV NODE_ENV=development
ENV PORT=3000

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install --frozen-lockfile

COPY prisma ./prisma

RUN pnpm prisma generate

COPY . .

RUN mkdir -p /app/exports/pdf /app/exports/html /app/exports/temp

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
